apiVersion: v1
kind: Service
metadata:
  name: api-service
  namespace: scraper-ftr
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 3002
  selector:
    app: api-service
---
apiVersion: v1
kind: Service
metadata:
  name: playwright-service
  namespace: scraper-ftr
spec:
  ports:
  - port: 3000
    targetPort: 3000
  selector:
    app: playwright-service 